# Build a package root holding one .Rd file and the rendered HTML of the man
# page Quarto produced from it, with the repo-action links Quarto writes when
# the site sets `repo-actions:`.
local_man_site <- function(
    topic,
    rd_lines,
    r_files = character(0),
    env = parent.frame()
) {
    root <- withr::local_tempdir(.local_envir = env)
    fs::dir_create(fs::path_join(c(root, "man")))
    fs::dir_create(fs::path_join(c(root, "R")))
    fs::dir_create(fs::path_join(c(root, "docs", "man")))

    if (length(rd_lines) > 0) {
        writeLines(
            rd_lines,
            fs::path_join(c(root, "man", paste0(topic, ".Rd")))
        )
    }
    for (f in r_files) {
        writeLines("NULL", fs::path_join(c(root, f)))
    }

    html <- fs::path_join(c(root, "docs", "man", paste0(topic, ".html")))
    writeLines(
        c(
            "<div class=\"toc-actions\"><ul>",
            sprintf(
                "<li><a href=\"https://github.com/user/pkg/edit/main/man/%s.qmd\" class=\"toc-action\">Edit this page</a></li>",
                topic
            ),
            sprintf(
                "<li><a href=\"https://github.com/user/pkg/blob/main/man/%s.qmd\" class=\"toc-action\">View source</a></li>",
                topic
            ),
            "<li><a href=\"https://github.com/user/pkg/issues\" class=\"toc-action\">Report an issue</a></li>",
            "</ul></div>"
        ),
        html
    )

    list(root = root, html = html)
}

roxygen_rd <- function(source_line) {
    c(
        "% Generated by roxygen2: do not edit by hand",
        source_line,
        "\\name{topic}",
        "\\title{Topic}"
    )
}

test_that("a roxygen-generated man page links at the R file it was written in", {
    site <- local_man_site(
        "calculate_summary",
        roxygen_rd("% Please edit documentation in R/calculate_summary.R"),
        r_files = "R/calculate_summary.R"
    )

    .rewrite_man_source_links(
        fs::path_join(c(site$root, "docs")),
        site$root
    )

    out <- paste(.readlines(site$html), collapse = "\n")
    expect_true(grepl(
        'href="https://github.com/user/pkg/blob/main/R/calculate_summary.R"',
        out,
        fixed = TRUE
    ))
    ### the "Edit this page" action names the same input file, so it is
    ### repointed too
    expect_true(grepl(
        'href="https://github.com/user/pkg/edit/main/R/calculate_summary.R"',
        out,
        fixed = TRUE
    ))
    expect_false(grepl(".qmd", out, fixed = TRUE))
    ### "Report an issue" is built from the repository URL alone
    expect_true(grepl(
        'href="https://github.com/user/pkg/issues"',
        out,
        fixed = TRUE
    ))
})

test_that("a hand-written man page links at the .Rd file, which is its source", {
    site <- local_man_site(
        "handwritten",
        c("\\name{handwritten}", "\\title{Handwritten}")
    )

    .rewrite_man_source_links(
        fs::path_join(c(site$root, "docs")),
        site$root
    )

    out <- paste(.readlines(site$html), collapse = "\n")
    expect_true(grepl(
        'href="https://github.com/user/pkg/blob/main/man/handwritten.Rd"',
        out,
        fixed = TRUE
    ))
    expect_false(grepl(".qmd", out, fixed = TRUE))
})

test_that("a topic documented in several R files links at the first of them", {
    ### roxygen2 wraps this comment at 80 characters, so a long list arrives
    ### as a block of `%` lines rather than as one line
    site <- local_man_site(
        "spread",
        c(
            "% Generated by roxygen2: do not edit by hand",
            "% Please edit documentation in R/spread_first.R,",
            "%   R/spread_second.R",
            "\\name{spread}",
            "\\title{Spread}"
        ),
        r_files = c("R/spread_first.R", "R/spread_second.R")
    )

    .rewrite_man_source_links(
        fs::path_join(c(site$root, "docs")),
        site$root
    )

    out <- paste(.readlines(site$html), collapse = "\n")
    expect_true(grepl(
        'href="https://github.com/user/pkg/blob/main/R/spread_first.R"',
        out,
        fixed = TRUE
    ))
})

test_that("a stale .Rd naming a deleted R file falls back to the .Rd", {
    site <- local_man_site(
        "stale",
        roxygen_rd("% Please edit documentation in R/deleted.R")
    )

    .rewrite_man_source_links(
        fs::path_join(c(site$root, "docs")),
        site$root
    )

    out <- paste(.readlines(site$html), collapse = "\n")
    expect_true(grepl(
        'href="https://github.com/user/pkg/blob/main/man/stale.Rd"',
        out,
        fixed = TRUE
    ))
})

test_that("a page with no .Rd behind it is left alone", {
    site <- local_man_site("orphan", character(0))

    .rewrite_man_source_links(
        fs::path_join(c(site$root, "docs")),
        site$root
    )

    out <- paste(.readlines(site$html), collapse = "\n")
    expect_true(grepl(
        'href="https://github.com/user/pkg/blob/main/man/orphan.qmd"',
        out,
        fixed = TRUE
    ))
})

test_that("a topic whose name carries regex metacharacters is matched literally", {
    site <- local_man_site(
        "sub-.foo",
        roxygen_rd("% Please edit documentation in R/subset.R"),
        r_files = "R/subset.R"
    )
    ### a second link on the same page, naming a topic that differs only where
    ### an unescaped `.` would match any character
    decoy <- paste0(
        '<a href="https://github.com/user/pkg/blob/main/man/sub-Xfoo.qmd"',
        ' class="toc-action">elsewhere</a>'
    )
    writeLines(c(.readlines(site$html), decoy), site$html)

    .rewrite_man_source_links(
        fs::path_join(c(site$root, "docs")),
        site$root
    )

    out <- paste(.readlines(site$html), collapse = "\n")
    expect_true(grepl(
        'href="https://github.com/user/pkg/blob/main/R/subset.R"',
        out,
        fixed = TRUE
    ))
    expect_true(grepl(
        'href="https://github.com/user/pkg/blob/main/man/sub-Xfoo.qmd"',
        out,
        fixed = TRUE
    ))
})

test_that("a link that is not a repo action is left alone", {
    ### same trailing path, same topic, but no `/blob/` or `/edit/` segment --
    ### so it is an ordinary link in the page body, not a repo action
    site <- local_man_site(
        "plain",
        roxygen_rd("% Please edit documentation in R/plain.R"),
        r_files = "R/plain.R"
    )
    body_link <- '<a href="https://example.org/man/plain.qmd">reference</a>'
    writeLines(c(.readlines(site$html), body_link), site$html)

    .rewrite_man_source_links(
        fs::path_join(c(site$root, "docs")),
        site$root
    )

    out <- paste(.readlines(site$html), collapse = "\n")
    expect_true(grepl(
        'href="https://example.org/man/plain.qmd"',
        out,
        fixed = TRUE
    ))
    ### the repo actions on the same page are still rewritten
    expect_true(grepl(
        'href="https://github.com/user/pkg/blob/main/R/plain.R"',
        out,
        fixed = TRUE
    ))
})

test_that("a body link to the same forge path is left alone", {
    ### it carries the `/blob/` segment, so only the missing `toc-action` class
    ### separates it from a genuine repo action
    site <- local_man_site(
        "plain",
        roxygen_rd("% Please edit documentation in R/plain.R"),
        r_files = "R/plain.R"
    )
    body_link <- paste0(
        '<a href="https://github.com/user/pkg/blob/main/man/plain.qmd">',
        "upstream source</a>"
    )
    writeLines(c(.readlines(site$html), body_link), site$html)

    .rewrite_man_source_links(
        fs::path_join(c(site$root, "docs")),
        site$root
    )

    out <- paste(.readlines(site$html), collapse = "\n")
    expect_true(grepl(
        '<a href="https://github.com/user/pkg/blob/main/man/plain.qmd">',
        out,
        fixed = TRUE
    ))
    ### the repo actions on the same page are still rewritten
    expect_true(grepl(
        'href="https://github.com/user/pkg/blob/main/R/plain.R"',
        out,
        fixed = TRUE
    ))
})

test_that("the toc-action class is matched as a token, not as a substring", {
    root <- withr::local_tempdir()
    html <- fs::path_join(c(root, "tok.html"))
    writeLines(
        c(
            ### a genuine repo action carrying a second class
            paste0(
                '<a href="https://github.com/user/pkg/blob/main/man/tok.qmd"',
                ' class="toc-action external">src</a>'
            ),
            ### a body link whose attribute merely ends in "class"
            paste0(
                '<a href="https://github.com/user/pkg/blob/main/man/tok.qmd"',
                ' data-class="toc-action">elsewhere</a>'
            ),
            ### and one whose class merely contains the name
            paste0(
                '<a href="https://github.com/user/pkg/blob/main/man/tok.qmd"',
                ' class="not-toc-action">elsewhere</a>'
            )
        ),
        html
    )

    .rewrite_man_source_links_one(html, "tok", "R/tok.R")

    out <- .readlines(html)
    expect_true(grepl("/blob/main/R/tok.R\"", out[1], fixed = TRUE))
    expect_true(grepl("/blob/main/man/tok.qmd\"", out[2], fixed = TRUE))
    expect_true(grepl("/blob/main/man/tok.qmd\"", out[3], fixed = TRUE))
})

test_that("non-ASCII text elsewhere on the page survives the rewrite", {
    ### Quarto writes UTF-8; a re-encode would touch every line, not only the
    ### rewritten one. The characters are built by code point so this file
    ### stays ASCII, per the repo's own convention.
    root <- withr::local_tempdir()
    html <- fs::path_join(c(root, "utf8.html"))
    accented <- paste0(
        "<p>fonction ",
        intToUtf8(c(233L, 99L, 114L, 105L, 116L, 101L)),
        " en fran",
        intToUtf8(c(231L, 97L, 105L, 115L)),
        " ",
        intToUtf8(8212L),
        " r",
        intToUtf8(c(233L, 115L, 117L, 109L, 233L)),
        "</p>"
    )
    writeLines(
        c(
            paste0(
                '<a href="https://github.com/user/pkg/blob/main/man/utf8.qmd"',
                ' class="toc-action">src</a>'
            ),
            accented
        ),
        html,
        useBytes = TRUE
    )

    .rewrite_man_source_links_one(html, "utf8", "R/utf8.R")

    after <- readLines(html, warn = FALSE, encoding = "UTF-8")
    expect_true(grepl("/blob/main/R/utf8.R", after[1], fixed = TRUE))
    ### byte-identical to what was written, whatever the session locale is
    expect_equal(charToRaw(after[2]), charToRaw(accented))
})

test_that("a source path is percent-encoded before it becomes an href", {
    ### `#` would otherwise start a fragment and the forge would receive
    ### `src/model` instead of the file
    root <- withr::local_tempdir()
    html <- fs::path_join(c(root, "enc.html"))
    writeLines(
        paste0(
            '<a href="https://github.com/user/pkg/blob/main/man/enc.qmd"',
            ' class="toc-action">src</a>'
        ),
        html
    )

    .rewrite_man_source_links_one(html, "enc", "src/model#v2.cpp")

    expect_equal(
        .readlines(html),
        paste0(
            '<a href="https://github.com/user/pkg/blob/main/src/model%23v2.cpp"',
            ' class="toc-action">src</a>'
        )
    )
})

test_that("a backslash in the source path cannot become a backreference", {
    ### `@backref` takes any path; encoding it removes the backslash before it
    ### can read as a backreference in the replacement
    root <- withr::local_tempdir()
    html <- fs::path_join(c(root, "backref.html"))
    writeLines(
        paste0(
            '<a href="https://github.com/user/pkg/blob/main/man/backref.qmd"',
            ' class="toc-action">src</a>'
        ),
        html
    )

    .rewrite_man_source_links_one(html, "backref", "src/code\\1.cpp")

    expect_equal(
        .readlines(html),
        paste0(
            '<a href="https://github.com/user/pkg/blob/main/src/code%5C1.cpp"',
            ' class="toc-action">src</a>'
        )
    )
})

test_that("a site with no repo-action links renders nothing to rewrite", {
    site <- local_man_site(
        "plain",
        roxygen_rd("% Please edit documentation in R/plain.R"),
        r_files = "R/plain.R"
    )
    html <- fs::path_join(c(site$root, "docs", "man", "plain.html"))
    writeLines("<p>No repo actions here.</p>", html)
    before <- .readlines(html)

    .rewrite_man_source_links(
        fs::path_join(c(site$root, "docs")),
        site$root
    )

    expect_equal(.readlines(html), before)
})

test_that("a site with no man/ directory is a no-op", {
    root <- withr::local_tempdir()
    fs::dir_create(fs::path_join(c(root, "docs")))
    expect_silent(.rewrite_man_source_links(
        fs::path_join(c(root, "docs")),
        root
    ))
})
