test_that(".rd_source_files() reads roxygen2's provenance comment", {
    root <- withr::local_tempdir()
    fs::dir_create(fs::path_join(c(root, "man")))
    fs::dir_create(fs::path_join(c(root, "R")))
    writeLines("NULL", fs::path_join(c(root, "R", "one.R")))
    writeLines("NULL", fs::path_join(c(root, "R", "two.R")))

    rd <- fs::path_join(c(root, "man", "topic.Rd"))
    writeLines(
        c(
            "% Generated by roxygen2: do not edit by hand",
            "% Please edit documentation in R/one.R, R/two.R",
            "\\name{topic}"
        ),
        rd
    )

    expect_equal(
        .rd_source_files(rd, src_dir = root),
        c("R/one.R", "R/two.R")
    )
})

test_that(".rd_source_files() reads a list wrapped across several lines", {
    root <- withr::local_tempdir()
    fs::dir_create(fs::path_join(c(root, "man")))
    fs::dir_create(fs::path_join(c(root, "R")))
    for (f in c("one.R", "two.R", "three.R")) {
        writeLines("NULL", fs::path_join(c(root, "R", f)))
    }

    rd <- fs::path_join(c(root, "man", "topic.Rd"))
    writeLines(
        c(
            "% Generated by roxygen2: do not edit by hand",
            "% Please edit documentation in R/one.R, R/two.R,",
            "%   R/three.R",
            "\\name{topic}"
        ),
        rd
    )

    expect_equal(
        .rd_source_files(rd, src_dir = root),
        c("R/one.R", "R/two.R", "R/three.R")
    )
})

test_that(".rd_source_files() reads a list that wrapped whole onto line two", {
    ### one filename long enough that nothing fits after "in" on the first
    ### line, so the comment carries no filename at all until the continuation
    root <- withr::local_tempdir()
    fs::dir_create(fs::path_join(c(root, "man")))
    fs::dir_create(fs::path_join(c(root, "R")))
    long <- "initial_weighting_fixed_regression_at_boundaries.R"
    writeLines("NULL", fs::path_join(c(root, "R", long)))

    rd <- fs::path_join(c(root, "man", "topic.Rd"))
    writeLines(
        c(
            "% Generated by roxygen2: do not edit by hand",
            "% Please edit documentation in",
            paste0("%   R/", long),
            "\\name{topic}"
        ),
        rd
    )

    expect_equal(.rd_source_files(rd, src_dir = root), paste0("R/", long))
})

test_that(".rd_source_files() keeps a percent sign that is part of a filename", {
    ### the continuation marker is stripped per line rather than by deleting
    ### every `%` in the block, which would corrupt this path
    root <- withr::local_tempdir()
    fs::dir_create(fs::path_join(c(root, "man")))
    fs::dir_create(fs::path_join(c(root, "R")))
    writeLines("NULL", fs::path_join(c(root, "R", "rate%change.R")))

    rd <- fs::path_join(c(root, "man", "topic.Rd"))
    writeLines(
        c(
            "% Generated by roxygen2: do not edit by hand",
            "% Please edit documentation in R/rate%change.R",
            "\\name{topic}"
        ),
        rd
    )

    expect_equal(.rd_source_files(rd, src_dir = root), "R/rate%change.R")
})

test_that(".rd_source_files() follows a wrap that fell inside a filename", {
    ### `strwrap()` breaks at any space, so a filename containing one wraps
    ### part-way through and the continuation does not follow a comma
    root <- withr::local_tempdir()
    fs::dir_create(fs::path_join(c(root, "man")))
    fs::dir_create(fs::path_join(c(root, "src")))
    spaced <- "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa module.cpp"
    writeLines("//", fs::path_join(c(root, "src", spaced)))

    rd <- fs::path_join(c(root, "man", "topic.Rd"))
    writeLines(
        c(
            "% Generated by roxygen2: do not edit by hand",
            "% Please edit documentation in src/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "%   module.cpp",
            "\\name{topic}"
        ),
        rd
    )

    expect_equal(
        .rd_source_files(rd, src_dir = root),
        paste0("src/", spaced)
    )
})

test_that(".rd_source_files() follows a wrap that fell inside two filenames", {
    ### the run has to be taken as a whole: after the first continuation the
    ### second filename is still incomplete, so a line-at-a-time rule stops one
    ### line early and loses both
    root <- withr::local_tempdir()
    fs::dir_create(fs::path_join(c(root, "man")))
    fs::dir_create(fs::path_join(c(root, "src")))
    first <- "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa module.cpp"
    second <- "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb helper.cpp"
    writeLines("//", fs::path_join(c(root, "src", first)))
    writeLines("//", fs::path_join(c(root, "src", second)))

    rd <- fs::path_join(c(root, "man", "topic.Rd"))
    writeLines(
        c(
            "% Generated by roxygen2: do not edit by hand",
            "% Please edit documentation in src/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "%   module.cpp, src/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
            "%   helper.cpp",
            "\\name{topic}"
        ),
        rd
    )

    expect_equal(
        .rd_source_files(rd, src_dir = root),
        paste0("src/", c(first, second))
    )
})

test_that(".rd_source_files() keeps a wrapped run that names one stale file", {
    ### a stale entry inside the run must not cost the entries beside it
    root <- withr::local_tempdir()
    fs::dir_create(fs::path_join(c(root, "man")))
    fs::dir_create(fs::path_join(c(root, "R")))
    writeLines("NULL", fs::path_join(c(root, "R", "kept.R")))

    rd <- fs::path_join(c(root, "man", "topic.Rd"))
    writeLines(
        c(
            "% Generated by roxygen2: do not edit by hand",
            "% Please edit documentation in src/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "%   deleted.cpp, R/kept.R",
            "\\name{topic}"
        ),
        rd
    )

    expect_equal(.rd_source_files(rd, src_dir = root), "R/kept.R")
})

test_that(".rd_source_files() stops at an INDENTED comment that is not a continuation", {
    ### indentation alone does not say where the block ends: this line is
    ### indented exactly like a continuation, and joining it would leave a
    ### filename the package does not have
    root <- withr::local_tempdir()
    fs::dir_create(fs::path_join(c(root, "man")))
    fs::dir_create(fs::path_join(c(root, "R")))
    writeLines("NULL", fs::path_join(c(root, "R", "foo.R")))

    rd <- fs::path_join(c(root, "man", "topic.Rd"))
    writeLines(
        c(
            "% Generated by roxygen2: do not edit by hand",
            "% Please edit documentation in R/foo.R",
            "%   package-specific generated comment",
            "\\name{topic}"
        ),
        rd
    )

    expect_equal(.rd_source_files(rd, src_dir = root), "R/foo.R")
})

test_that(".rd_source_files() stops at a comment that is not a continuation", {
    ### roxygen2 wraps with `%   `, so a singly-spaced `%` line after the block
    ### is somebody else's comment and must not be read as more filenames
    root <- withr::local_tempdir()
    fs::dir_create(fs::path_join(c(root, "man")))
    fs::dir_create(fs::path_join(c(root, "R")))
    writeLines("NULL", fs::path_join(c(root, "R", "foo.R")))

    rd <- fs::path_join(c(root, "man", "topic.Rd"))
    writeLines(
        c(
            "% Generated by roxygen2: do not edit by hand",
            "% Please edit documentation in R/foo.R",
            "% package-specific generated comment",
            "\\name{topic}"
        ),
        rd
    )

    expect_equal(.rd_source_files(rd, src_dir = root), "R/foo.R")
})

test_that(".rd_source_files() ignores the sentence outside roxygen2's header", {
    ### a hand-written .Rd is free to contain that sentence anywhere; only
    ### roxygen2's banner on line 1 with the backref on line 2 means it wrote
    ### the file
    root <- withr::local_tempdir()
    fs::dir_create(fs::path_join(c(root, "man")))
    fs::dir_create(fs::path_join(c(root, "R")))
    writeLines("NULL", fs::path_join(c(root, "R", "foo.R")))

    rd <- fs::path_join(c(root, "man", "topic.Rd"))
    writeLines(
        c(
            "\\name{topic}",
            "\\title{Topic}",
            "\\details{",
            "% Please edit documentation in R/foo.R",
            "}"
        ),
        rd
    )

    expect_equal(.rd_source_files(rd, src_dir = root), character(0))
    expect_equal(.man_source_path("topic", src_dir = root), "man/topic.Rd")
})

test_that(".rd_source_files() rejects a continuation that begins with a comma", {
    ### roxygen2 joins the list with ", " and wraps at a space, so the comma is
    ### always carried on the end of the preceding filename -- a line starting
    ### with one is somebody else's comment, whatever files it names
    root <- withr::local_tempdir()
    fs::dir_create(fs::path_join(c(root, "man")))
    fs::dir_create(fs::path_join(c(root, "R")))
    writeLines("NULL", fs::path_join(c(root, "R", "existing.R")))

    rd <- fs::path_join(c(root, "man", "topic.Rd"))
    writeLines(
        c(
            "% Generated by roxygen2: do not edit by hand",
            "% Please edit documentation in R/deleted.R",
            "%   , R/existing.R",
            "\\name{topic}"
        ),
        rd
    )

    expect_equal(.rd_source_files(rd, src_dir = root), character(0))
})

test_that(".rd_source_files() returns nothing for a hand-written .Rd", {
    root <- withr::local_tempdir()
    fs::dir_create(fs::path_join(c(root, "man")))
    rd <- fs::path_join(c(root, "man", "topic.Rd"))
    writeLines(c("\\name{topic}", "\\title{Topic}"), rd)

    expect_equal(.rd_source_files(rd, src_dir = root), character(0))
})

test_that(".rd_source_files() drops files the package no longer has", {
    root <- withr::local_tempdir()
    fs::dir_create(fs::path_join(c(root, "man")))
    fs::dir_create(fs::path_join(c(root, "R")))
    writeLines("NULL", fs::path_join(c(root, "R", "kept.R")))

    rd <- fs::path_join(c(root, "man", "topic.Rd"))
    writeLines(
        c(
            "% Generated by roxygen2: do not edit by hand",
            "% Please edit documentation in R/gone.R, R/kept.R",
            "\\name{topic}"
        ),
        rd
    )

    expect_equal(.rd_source_files(rd, src_dir = root), "R/kept.R")
})

test_that(".rd_source_files() returns nothing for a file that is not there", {
    root <- withr::local_tempdir()
    expect_equal(
        .rd_source_files(
            fs::path_join(c(root, "man", "absent.Rd")),
            src_dir = root
        ),
        character(0)
    )
})

test_that(".man_source_path() falls back to the .Rd and reports a missing topic", {
    root <- withr::local_tempdir()
    fs::dir_create(fs::path_join(c(root, "man")))
    writeLines("\\name{topic}", fs::path_join(c(root, "man", "topic.Rd")))

    expect_equal(.man_source_path("topic", src_dir = root), "man/topic.Rd")
    expect_null(.man_source_path("absent", src_dir = root))
})
