test_that(".rd_source_files() reads roxygen2's provenance comment", {
    root <- withr::local_tempdir()
    fs::dir_create(fs::path_join(c(root, "man")))
    fs::dir_create(fs::path_join(c(root, "R")))
    writeLines("NULL", fs::path_join(c(root, "R", "one.R")))
    writeLines("NULL", fs::path_join(c(root, "R", "two.R")))

    rd <- fs::path_join(c(root, "man", "topic.Rd"))
    writeLines(
        c(
            "% Generated by roxygen2: do not edit by hand",
            "% Please edit documentation in R/one.R, R/two.R",
            "\\name{topic}"
        ),
        rd
    )

    expect_equal(
        .rd_source_files(rd, src_dir = root),
        c("R/one.R", "R/two.R")
    )
})

test_that(".rd_source_files() reads a list wrapped across several lines", {
    root <- withr::local_tempdir()
    fs::dir_create(fs::path_join(c(root, "man")))
    fs::dir_create(fs::path_join(c(root, "R")))
    for (f in c("one.R", "two.R", "three.R")) {
        writeLines("NULL", fs::path_join(c(root, "R", f)))
    }

    rd <- fs::path_join(c(root, "man", "topic.Rd"))
    writeLines(
        c(
            "% Generated by roxygen2: do not edit by hand",
            "% Please edit documentation in R/one.R, R/two.R,",
            "%   R/three.R",
            "\\name{topic}"
        ),
        rd
    )

    expect_equal(
        .rd_source_files(rd, src_dir = root),
        c("R/one.R", "R/two.R", "R/three.R")
    )
})

test_that(".rd_source_files() reads a list that wrapped whole onto line two", {
    ### one filename long enough that nothing fits after "in" on the first
    ### line, so the comment carries no filename at all until the continuation
    root <- withr::local_tempdir()
    fs::dir_create(fs::path_join(c(root, "man")))
    fs::dir_create(fs::path_join(c(root, "R")))
    long <- "initial_weighting_fixed_regression_at_boundaries.R"
    writeLines("NULL", fs::path_join(c(root, "R", long)))

    rd <- fs::path_join(c(root, "man", "topic.Rd"))
    writeLines(
        c(
            "% Generated by roxygen2: do not edit by hand",
            "% Please edit documentation in",
            paste0("%   R/", long),
            "\\name{topic}"
        ),
        rd
    )

    expect_equal(.rd_source_files(rd, src_dir = root), paste0("R/", long))
})

test_that(".rd_source_files() returns nothing for a hand-written .Rd", {
    root <- withr::local_tempdir()
    fs::dir_create(fs::path_join(c(root, "man")))
    rd <- fs::path_join(c(root, "man", "topic.Rd"))
    writeLines(c("\\name{topic}", "\\title{Topic}"), rd)

    expect_equal(.rd_source_files(rd, src_dir = root), character(0))
})

test_that(".rd_source_files() drops files the package no longer has", {
    root <- withr::local_tempdir()
    fs::dir_create(fs::path_join(c(root, "man")))
    fs::dir_create(fs::path_join(c(root, "R")))
    writeLines("NULL", fs::path_join(c(root, "R", "kept.R")))

    rd <- fs::path_join(c(root, "man", "topic.Rd"))
    writeLines(
        c(
            "% Generated by roxygen2: do not edit by hand",
            "% Please edit documentation in R/gone.R, R/kept.R",
            "\\name{topic}"
        ),
        rd
    )

    expect_equal(.rd_source_files(rd, src_dir = root), "R/kept.R")
})

test_that(".rd_source_files() returns nothing for a file that is not there", {
    root <- withr::local_tempdir()
    expect_equal(
        .rd_source_files(fs::path_join(c(root, "man", "absent.Rd")), root),
        character(0)
    )
})

test_that(".man_source_path() falls back to the .Rd and reports a missing topic", {
    root <- withr::local_tempdir()
    fs::dir_create(fs::path_join(c(root, "man")))
    writeLines("\\name{topic}", fs::path_join(c(root, "man", "topic.Rd")))

    expect_equal(.man_source_path("topic", src_dir = root), "man/topic.Rd")
    expect_null(.man_source_path("absent", src_dir = root))
})
