.rd2qmd <- function(source_file, target_dir, path) {
    if (missing(source_file) || !file.exists(source_file)) {
        stop("source_file must be a valid file path.", call. = FALSE)
    }
    if (missing(target_dir) || !dir.exists(target_dir)) {
        stop("target_dir must be a valid directory.", call. = FALSE)
    }
    # R does not apply `.doc_type()`'s own `path = "."` default to an argument
    # the caller never supplied, so without this guard an omitted `path`
    # reaches it and fails with 'argument "path" is missing, with no default'.
    # Only directory-ness is checked here; `.doc_type()` reports the rest.
    if (missing(path) || !dir.exists(path)) {
        stop("path must be a valid directory.", call. = FALSE)
    }

    tool <- .doc_type(path)

    # Rd -> html
    rd <- tools::parse_Rd(source_file)
    tmp_html <- paste0(tempfile(), ".html")
    # the default for "toc" changed in R 4.6.0, so we need to set it explicitly
    tools::Rd2HTML(rd, out = tmp_html, toc = FALSE)

    # superfluous header and footer
    tmp <- .readlines(tmp_html)
    tmp <- tmp[(grep("</table>$", tmp)[1] + 1):length(tmp)]
    tmp <- utils::head(tmp, -4)

    # first column (odd entries) of table in Arguments should not be wrapped
    idx <- grep("<td>", tmp, fixed = TRUE)
    idx <- idx[seq_along(idx) %% 2 == 1]
    tmp[idx] <- sub(
        "<td>",
        paste0(
            '<td style = "white-space: ',
            # https://github.com/etiennebacher/altdoc/issues/306
            if (tool != "mkdocs") "collapse" else "nowrap",
            '; font-family: monospace; vertical-align: top">'
        ),
        tmp[idx],
        fixed = TRUE
    )

    # escape the $ in man pages otherwise it thinks it is a latex equation and
    # doesn't escape symbols between two $.
    tmp <- gsub("\\$", "\\\\$", tmp)

    # process \doi{...} tags that were expanded to \Sexpr[results=rd]{tools:::Rd_expr_doi("...")}
    tmp <- gsub(
        "(\\\\Sexpr\\[results=rd\\]\\{tools:::Rd_expr_doi\\(\\\")([^\\\"]+)(\\\"\\)\\})",
        "[doi:\\2](https://doi.org/\\2)",
        tmp
    )

    # examples: evaluate code blocks (assume examples are always last)
    pkg <- .pkg_name(path)
    pkg_load <- paste0("library(\"", pkg, "\")")
    idx <- which(tmp == "<h3>Examples</h3>")

    if (length(idx) == 1) {
        # Read the examples from the parsed Rd tree rather than the rendered
        # HTML, so that `\dontrun{}` and `\donttest{}` are honored per block
        # instead of switching evaluation off for the whole page (#38).
        blocks <- .rd_example_blocks(rd)

        # An `@examplesIf` condition that does not hold disables every block,
        # since the examples were written on the assumption it did.
        condition <- .rd_examples_if_condition(rd)
        if (!is.null(condition)) {
            holds <- try(eval(parse(text = condition)), silent = TRUE)
            if (!isTRUE(holds)) {
                blocks <- lapply(blocks, function(b) {
                    b$eval <- FALSE
                    b
                })
            }
        }

        tmp <- c(tmp[2:idx], .example_chunks(blocks, pkg_load = pkg_load))
    }

    # cleanup equations
    tmp <- gsub(
        '<code class="reqn">(.*?)&gt;(.*?)</code>',
        '<code class="reqn">\\1>\\2</code>',
        tmp
    )
    tmp <- gsub(
        '<code class="reqn">(.*?)&lt;(.*?)</code>',
        '<code class="reqn">\\1<\\2</code>',
        tmp
    )
    tmp <- gsub('<code class="reqn">(.*?)</code>', "\\$\\1\\$", tmp)

    # cleanup code
    tmp <- gsub("&#8288;", "", tmp, fixed = TRUE)

    # title
    title <- tmp[grep("^<h2", tmp)[1]:grep("</h2>", tmp)[1]]
    title <- paste(title, collapse = " ")
    title <- gsub("<h2[^>]*>(.*)</h2>", "## \\1 {.unnumbered}\n", title)
    tmp <- tmp[(grep("</h2>", tmp)[1] + 1):length(tmp)]
    tmp <- c(title, tmp)

    # Fix title level (use ## and not <h2> so that the TOC can be generated by
    # mkdocs)
    tmp <- gsub("<.h2>", "", tmp)
    tmp <- gsub("<h3>", "### ", tmp, fixed = TRUE)
    tmp <- gsub("</h3>", "", tmp, fixed = TRUE)

    # paragraph tags are unnecessary in markdown
    tmp <- gsub("<p>", "", tmp, fixed = TRUE)
    tmp <- gsub("</p>", "", tmp, fixed = TRUE)

    # write to file
    fn <- file.path(target_dir, sub("Rd$", "qmd", basename(source_file)))
    writeLines(tmp, con = fn)
}
