# The R source files a roxygen2-generated .Rd file was written from.
#
# roxygen2 records them in a comment block at the top of every file it
# generates:
#
#     % Generated by roxygen2: do not edit by hand
#     % Please edit documentation in R/foo.R, R/bar.R
#
# The list is wrapped at 80 characters with continuation lines prefixed by
# "%", so it is read as a block rather than as a single line.
#
# Returns `character(0)` for a hand-written .Rd, which carries no such comment:
# there the .Rd file is itself the source. Files the comment names but the
# package no longer has are dropped too, so a stale .Rd cannot produce a link
# to a file nobody can open.
.rd_source_files <- function(rd_file, src_dir) {
    if (!fs::file_exists(rd_file)) {
        return(character(0))
    }

    lines <- .readlines(rd_file)
    start <- grep("^%\\s*Please edit documentation in\\s", lines)
    if (length(start) == 0) {
        return(character(0))
    }
    start <- start[1]

    # Every `%` line after the first belongs to the wrapped list: roxygen2
    # writes this comment last, so the Rd markup itself starts on the next
    # non-comment line.
    end <- start
    while (end < length(lines) && grepl("^%", lines[end + 1])) {
        end <- end + 1
    }

    block <- paste(lines[start:end], collapse = " ")
    block <- sub("^%\\s*Please edit documentation in\\s+", "", block)
    block <- gsub("%", " ", block, fixed = TRUE)

    files <- trimws(strsplit(block, ",", fixed = TRUE)[[1]])
    files <- files[nzchar(files)]

    Filter(
        function(f) fs::file_exists(fs::path_join(c(src_dir, f))),
        files
    )
}
