# The R source files a roxygen2-generated .Rd file was written from.
#
# roxygen2 records them in a comment block at the top of every file it
# generates:
#
#     % Generated by roxygen2: do not edit by hand
#     % Please edit documentation in R/foo.R, R/bar.R
#
# The list is wrapped at 80 characters with `strwrap(prefix = "%   ")`, which
# breaks it only at a space -- so a continuation line exists only where what
# has been read so far ends in a comma, or where the first line ended at "in"
# and carries no filename at all. Requiring that, rather than reading every
# indented `%` line, is what keeps an unrelated Rd comment following the block
# out of the file list: Rd allows one there, and roxygen2 is not the only thing
# that writes .Rd files.
#
# Each line's own prefix is stripped before the block is joined, so a `%` that
# is part of a filename is left alone.
#
# Returns `character(0)` for a hand-written .Rd, which carries no such comment:
# there the .Rd file is itself the source. Files the comment names but the
# package no longer has are dropped too, so a stale .Rd cannot produce a link
# to a file nobody can open.
.rd_source_files <- function(rd_file, src_dir) {
    if (!fs::file_exists(rd_file)) {
        return(character(0))
    }

    lines <- .readlines(rd_file)
    start <- grep("^%\\s*Please edit documentation in", lines)
    if (length(start) == 0) {
        return(character(0))
    }
    start <- start[1]

    block <- sub(
        "^%\\s*Please edit documentation in\\s*",
        "",
        lines[start]
    )

    i <- start + 1
    while (
        i <= length(lines) &&
            grepl(",$|^$", block) &&
            grepl("^%\\s{2,}\\S", lines[i])
    ) {
        block <- paste(block, sub("^%\\s+", "", lines[i]))
        i <- i + 1
    }

    files <- trimws(strsplit(block, ",", fixed = TRUE)[[1]])
    files <- files[nzchar(files)]

    Filter(
        function(f) fs::file_exists(fs::path_join(c(src_dir, f))),
        files
    )
}
