# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: flir

jobs:
  flir:
    runs-on: macOS-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: flir-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - uses: r-lib/actions/setup-r@d3c5be51b12e724e68f33216ca3c148b66d5f0b6 # v2.12.1

      - name: Install flir
        run: install.packages("flir")
        shell: Rscript {0}

      - name: Run flir
        run: flir::lint()
        shell: Rscript {0}
        env:
          FLIR_ERROR_ON_LINT: true
